### ISSUE TITLE
Permission to sell hardware

### ISSUE THREAD

**Issue by hackwin** [mafrmt00/Apple_II_Keyboard#4]
Do you mind if I sell this hardware with your sketch on eBay?

**Comment by mafrmt00** [comment]
No problem, please send me a link to the listing. I'd like to see how it's selling.

**Comment by hackwin** [comment]
I bundled the keyboard adapter with an Apple II that was fixed up.
https://www.ebay.com/itm/284514066122

A fake PCB card that has holes to mount the Arduino Uno would be nice.
