### ISSUE TITLE
Question on debug output

### ISSUE THREAD

**Issue by timmcross** [mafrmt00/Apple_II_Keyboard#5]
Should changing this

Prs.bDebugPrint = false;

to true

enable more output on the Serial monitor?  Should keys from the USB keyboard also be displayed on the Serial monitor?  After compiling and uploading this sketch, I don't see any output after the welcome message.

Thanks!

**Comment by mafrmt00** [comment]
The serial output is for debugging only.
If everything works, you don't need it. But if you have problems, enable debugprints and you should see if your usb input is working.

**Comment by timmcross** [comment]
Ok, thanks.  I noticed that the 3.3 rail is actually 3.9v so I wonder if the chips on the USB shield are dead.  Reset button works but I don't think it recognizes any of my keyboards (including a K120).  I have ordered another shield.

**Comment by mafrmt00** [comment]
5V is what we want, because the Apple II runs on 5V. Have you set the jumpers on the USB-Shield according to the picture?
(I don't think that 3.9V would kill the chip.)

**Comment by timmcross** [comment]
Yes, 5v vbus is set and the 5v and 3.3v Conn's are bridged.

**Comment by mafrmt00** [comment]
I think I made some changes to the host shield library, so make sure to use the one from the repo.

**Comment by timmcross** [comment]
Yeah, I was using yours since the latest wouldn't compile.  I also found a test program out there for the shield.  It goes through the initial test fine, but when it is waiting for a device, nothing I connect seems to register.  I have another shield on order, I will try that.

**Comment by timmcross** [comment]
I tried another shield from Amazon and this one doesn't even respond to the revision query from the qc test program.  Guess these knock-off shields don't work very well.  Looks like I will have to skip this project.  Thanks for your help!
