### ISSUE TITLE
Standalone usage

### ISSUE THREAD

**Issue by meup** [mafrmt00/Apple_II_Keyboard#6]
As the code is now, the setup only works when attached to a computer and a serial monitor is connected.
Since I wanted to use this as a standalone converter, I had to logically remove all references to Serial.
You might want to mention this in the description.

I used an Arduino Pro Micro and a USB Mini Host Shield to make my converter.
Note that the Mini Host Shield requires a power supply mod
(see https://chome.nerpa.tech/usb-host-shield-hardware-manual/ section 4).
The 5V power from the keyboard connector can then be hooked up to the "raw" power input pin.
Also the reset pin needs to be routed with a wire.
Here's a picture of my adapter: https://photos.app.goo.gl/D7rBnEV14vFqLHt28

**Comment by mafrmt00** [comment]
As you can see in the pinout the 5V pin is connected, so the Uno is powered by the Apple II.
Also the Uno has absolutely no problem functioning without a USB connection.

**Comment by meup** [comment]
With the 2.2.1 version of the Arduino IDE and the hardware I used, the sketch as written will not output characters to the Apple II unless a serial connection is made.  That is a fact.  I'm not writing to give you a hard time, but to help others who may face this problem.

**Comment by mafrmt00** [comment]
You are using a pro micro. I have absolutely no Idea how the built in USB influences the behaviour. On a ATMEG328 there is no influence at all if the serial interface is connected or not.
![keyboard_adapter](https://github.com/mafrmt00/Apple_II_Keyboard/assets/11454230/6f87983a-f3d5-4236-bffe-25b83e972887)
But you have to wait just a little bit and you can have the dedicated HW.

**Comment by meup** [comment]
Since the MEGA32U4 does all the USB communication itself, it seems like that could be the reason for the difficulty.
But you might also consider using it for your dedicated HW, since it may reduce the BOM by 1 IC and perhaps also the form factor of the final result.  I'm actually not sure what U2 is for in the provided image?  A level converter should not be needed if both chips are running at 3.3V.

**Comment by mafrmt00** [comment]
Of course, today there are many possibilities for a USB-Host implementation. But I stuck to the HW my SW is made for. ATMEGA328 and MAX3421E.

The Apple II is 5V so the 328 also runs on 5V but the MAX3421E is 3.3V only and a level shifter for SPI is needed.

And with that interface you can even use it the other way round and connect a Apple II Keyboard to it.

If I'd start the whole thing today, I'd probably use a ESP32 and level shifters on the keyboard side, but then I really don't like adding a peripheral to a retrocomputer that easily could emulate the whole thing.

**Comment by meup** [comment]
If you want to use the device in reverse, that's a better reason to use Atmega32U4, since it can act as a HID device easily.

**Comment by mafrmt00** [comment]
If I ever make a V2.0 I'll use a ESP32 and make the whole thing fit on the dip footprint. With a ESP32 it can have Bluetooth and USB.

But the project is old and only with the recent development in PCB prices I finally made a custom PCB.

The PCB is beeing manufactured now, if it works I will ad the design files to the repo.
